name: Build and Push to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/build-push.yaml'
  workflow_dispatch:

env:
  ECR_REPO: 851725266652.dkr.ecr.ap-south-1.amazonaws.com/bootcamp-dev-2-tier-flask
  AWS_REGION: ap-south-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REPO }}

      - name: Build, Tag, and Push Docker Image
        run: |
          cd src
          docker build -t ${{ env.ECR_REPO }}:day6 .
          docker push ${{ env.ECR_REPO }}:day6
